### ISSUE TITLE
Feature Request: Pass cluster bounds to the Cluster Marker component

### ISSUE THREAD

**Issue by derwaldgeist** [urbica/react-map-gl-cluster#26]
I love these clusters, thanks a lot for implementing this package.

In my use-case, we're using the clusters on a huge world map. I would like to make them interactive, so a user can click on a cluster and the map zooms in to show its contents. For this, I would need the bounds of the area covered by the cluster, so I can exactly zoom in to this area. It would be awesome if the bounds (or the radius of the cluster) would be part of the information passed into the cluster marker component.

**Comment by stepankuzmin** [comment]
Hi @derwaldgeist 

You can achieve this now using supercluster instance, as shown in [example](https://urbica.github.io/react-map-gl-cluster/)

Passing cluster expansion zoom to every component may be expensive, although it needs benchmarking.

**Comment by derwaldgeist** [comment]
Woah, that's uber-cool, thanks!

**Comment by derwaldgeist** [comment]
I tried it, but I noticed that the zoom level is way too high most of the times, so the markers won't actually fit into the bounds. I have to zoom quite a way out to see them. What might go wrong here?
